config/routes.rb
Rails.application.routes.draw do
  resources :widgets

  resources :customers, except: [:show]
  get 'customers/widget_counts'

  devise_for :users, :controllers => { invitations: 'devise/invitations', omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :user_links, only: [:create, :destroy]

  resources :users do
    post :invite, :on => :collection
  end
  root to: 'visitors#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :user_links
  before_validation :downcase_subdomain
  after_create :create_customer_tenant

  scope :active, -> { where(active: true) }
  scope :inactive, -> { where(active: false) }

  after_initialize :set_defaults

  def set_defaults
    self.active ||= true if self.new_record?
  end

  def self.current
    Customer.active.find_by(subdomain: Apartment::Tenant.current)
  end

  # Find any destination links for a given user in this customer
  def destination_user_links(user)
    this_subdomain = Apartment::Tenant.current
    return nil if self.subdomain == this_subdomain

    Apartment::Tenant.switch!(self.subdomain)
    user_links = UserLink.where(link_user_id: user.id)
    Apartment::Tenant.switch!(this_subdomain)

    user_links
  end

  private
  def create_customer_tenant
    Apartment::Tenant.create(subdomain)
  end

  def downcase_subdomain
    if self.subdomain
      self.subdomain.downcase!
    end
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
    @current_customer_id = Customer.current&.id
    @linked_customer_ids = current_user&.origin_user_links&.map(&:link_customer_id) || []
  end

  def widget_counts
    customers = Customer.select(:id, :subdomain)
    sql = customers.map{|c| "SELECT #{c.id} AS customer_id, COUNT(*) AS count FROM #{c.subdomain}.widgets\n"}.
      join("UNION ALL\n")
    counts = ActiveRecord::Base.connection.execute(sql)
    render json: {current_customer_id: session[:customer_id],
        # current_user_id: session["warden.user.user.key"]&.first&.first,
        current_user_id: session["link_user_id"],
        counts: counts
      }
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
    @customerUsers = []
    if @customer.present?
      subdomain = @customer.subdomain

      # Apartment::Tenant.switch!(subdomain) do
      #   @customerUsers = User.all
      # end
    end
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)
    @customer.active = true
    respond_to do |format|
      if @customer.save

        if params[:customer][:authentication_type] == '0'
          # Switch to subdomain and invite an admin.
          Apartment::Tenant.switch(params[:customer][:subdomain]) do
            User.invite!(:email => params[:customer][:email], :name => 'Administrator')
            user = User.find_by_email(params[:customer][:email])
            if user.present?
              user.role = :admin
              user.save
            end
          end
        end

        format.html { redirect_to customers_path, notice: 'Tenant was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        if params[:customer][:authentication_type] == '0'
          # Switch to subdomain and invite an admin.
          Apartment::Tenant.switch( @customer.subdomain) do
            User.invite!(:email => params[:customer][:email], :name => 'Administrator')
            user = User.find_by_email(params[:customer][:email])
            if user.present?
              user.role = :admin
              user.save
            end
          end
        end
        format.html { redirect_to customers_path, notice: 'Tenant was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Tenant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:subdomain, :email, :idp_login, :fingerprint, :authentication_type)
    end
end

app/views/customers/_form.html.erb
<%= form_for(customer) do |f| %>
  <% if customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <br>
  <div class="field">
    <%= f.label :subdomain %>
    <%= f.text_field :subdomain %>
  </div>
    <br>
    <div class="field">
      <%= f.label :authentication_type %><br />
      <%= f.label :authentication_type, "Email & Password"  %>
      <%= f.radio_button :authentication_type, 0, :checked => ( customer.authentication_type == 0 ? 'checked' : '' ) %>
      <%= f.label :authentication_type, "SAML" %>
      <%= f.radio_button :authentication_type, 1, :checked => (customer.authentication_type == 1 ? 'checked' : '') %>
    </div>

    <div class="field" id="email_info" style="<%=customer.authentication_type != 0 ? 'display: none;':''%>">
      <%= f.label :email %>
      <%= f.text_field :email %>
    </div>

    <div class="field" id="saml_info" style="<%=customer.authentication_type != 1 ? 'display: none;':''%>">
      <%= f.label :fingerprint %>
      <%= f.text_field :fingerprint %><br>
      <%= f.label :idp_login %>
      <%= f.text_field :idp_login %>
    </div>

  <div class="actions">
    <% if customer.id.nil? %>
      <%= f.submit 'Create Tenant', :class => 'button-xs customer-submit' %>
    <% else %>
      <%= f.submit 'Update Tenant', :class => 'button-xs customer-submit' %>
    <% end %>
  </div>
<% end %>

<% unless @customerUsers.nil?  %>
<h3> Users </h3>
<table class="table">
  <tbody>
    <% @customerUsers.each do |user| %>
        <tr>
          <td>
            <%= user.email %>
          </td>
        </tr>
    <% end %>
  </tbody>
</table>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing Tenant</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<p id="notice"><%= notice %></p>

<% unless @current_customer_id.nil? %>
<h1>From <%= Customer.current.subdomain %> you can go to:</h1>
<% end %>

<table class="customer-table">
  <thead>
    <tr>
      <th>Subdomain</th>
      <th colspan="<%= @current_customer_id.nil? ? 3 : 2 %>"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.subdomain %></td>
        <td>
          <%= link_to 'Navigate', "http://#{customer.subdomain}.lvh.me:3000" %>
        </td>
        <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
        <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tenant', new_customer_path %>

app/views/customers/new.html.erb
<h3>New Tenant</h3>

<%= render 'form', customer: @customer %>

<%= link_to 'Back', customers_path, :class => 'button-xs' %>