config/routes.rb
Rails.application.routes.draw do
  resources :widgets

  resources :customers, except: [:show]
  get 'customers/widget_counts'

  devise_for :users, :controllers => { invitations: 'devise/invitations', omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :user_links, only: [:create, :destroy]

  resources :users do
    post :invite, :on => :collection
  end
  root to: 'visitors#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/user.rb
class User < ApplicationRecord

  enum role: [:user, :admin]
  enum state: [:active, :suspend]

  after_initialize :set_default_role, :if => :new_record?
  after_initialize :set_default_state, :if => :new_record?

  has_many :origin_user_links, class_name: "UserLink", foreign_key: :link_user_id

  def set_default_role
    self.role ||= :user
  end

  def set_default_state
    self.state ||= :active
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :invitable, :invite_for => 2.weeks

  devise :omniauthable, :omniauth_providers => [:saml]

  def self.find_for_saml_oauth(auth, signed_in_resource=nil)
    uid = ''
    auth.extra.raw_info.each do |key, val|
      uid = val[0]
      break
    end
    # user = User.where(:provider => auth.provider, :uid => auth.uid).first
    user = User.where(:provider => auth.provider, :uid => uid).first

    name = auth.info.name || 'no name'
    email = auth.info.email || Faker::Internet.email

    unless user
      user = User.create(name: name,
                         provider:auth.provider,
                         uid:uid,
                         email:email,
                         password:Devise.friendly_token[0,20]
      )
    end
    user
  end


end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  skip_before_action :verify_authenticity_token, only: :saml

  def saml
    subdomain = request.env["omniauth.params"]["subdomain"]
    # this_subdomain = Apartment::Tenant.current
    subdomain = request.subdomain

    Apartment::Tenant.switch!(subdomain)
    @user = User.find_for_saml_oauth(request.env["omniauth.auth"], current_user)
    unless @user.id?
      @user.save!
    end
    sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated

    set_flash_message(:notice, :success, :kind => "simplesamlphp") if is_navigational_format?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_only, :except => :show

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless current_user.admin?
      unless @user == current_user
        redirect_to root_path, :alert => "Access denied."
      end
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  def invite
    User.invite!(:email => params[:user][:email], :name => params[:user][:name])
    redirect_to users_path, :notice => "Invited."
  end

  private

  def admin_only
    unless current_user.admin?
      redirect_to root_path, :alert => "Access denied."
    end
  end

  def secure_params
    params.require(:user).permit(:role, :state)
  end



end

app/views/users/invitations/edit.html.erb
<h2><%= t 'devise.invitations.edit.header' %></h2>

<%= form_for resource, :as => resource_name, :url => invitation_path(resource_name), :html => { :method => :put } do |f| %>
  <%= devise_error_messages! %>
  <%= f.hidden_field :invitation_token, readonly: true %>

  <% if f.object.class.require_password_on_accepting %>
  <p><%= f.label :password %><br />
  <%= f.password_field :password %></p>

  <p><%= f.label :password_confirmation %><br />
  <%= f.password_field :password_confirmation %></p>
  <% end %>

  <p><%= f.submit t("devise.invitations.edit.submit_button") %></p>
<% end %>

app/views/users/invitations/new.html.erb
<h2><%= t "devise.invitations.new.header" %></h2>

<%= form_for resource, :as => resource_name, :url => invitation_path(resource_name), :html => {:method => :post} do |f| %>
  <%= devise_error_messages! %>

<% resource.class.invite_key_fields.each do |field| -%>
  <p><%= f.label field %><br />
  <%= f.text_field field %></p>
<% end -%>

  <p><%= f.submit t("devise.invitations.new.submit_button") %></p>
<% end %>