config/routes.rb
Rails.application.routes.draw do
  resources :widgets

  resources :customers, except: [:show]
  get 'customers/widget_counts'

  devise_for :users, :controllers => { invitations: 'devise/invitations', omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :user_links, only: [:create, :destroy]

  resources :users do
    post :invite, :on => :collection
  end
  root to: 'visitors#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-dismissible alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
    <% if Customer.current&.id != 0 && !Customer.current.nil? %>
      <% if Customer.current.authentication_type == 0 %>
          <li><%= link_to 'Sign in', new_user_session_path %></li>
          <li><%= link_to 'Sign up', new_user_registration_path %></li>
      <% else %>
          <li><%= link_to "Sign in with SAML", "#{user_saml_omniauth_authorize_path()}?subdomain=#{Apartment::Tenant.current}" %></li>
      <% end %>
    <% else %>
      <li><%= link_to 'Sign in', new_user_session_path %></li>
    <% end %>
<% end %>
<% if user_signed_in? %>
  <% if current_user.try(:admin?) %>
    <li><%= link_to 'Users', users_path %></li>
        <% if Customer.current&.id == 0 || Customer.current&.id.nil? %>
            <li><%= link_to 'Tenants', customers_path %></li>
        <% end %>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
        <%= render 'layouts/nav_links_for_auth' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%#= link_to 'About', page_path('about') %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Tenant Management" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Tenant Management" %>">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <!--
    <% unless devise_controller? || current_user.nil? %>
    	Welcome, <%= current_user.email %> to <%= Customer.current&.subdomain %>!<br>
    	<%= link_to "Logout", destroy_user_session_path, method: :delete %><br>
    <% end %>

    <%= yield %>
  -->
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </main>
  </body>
</html>